# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$gJVMoNdN9SYMP5pOM5IRFOu0dhbpZrJKL1YJdtNTgO8R1Jkw.Tf9W  #timemaster
                        roles: 'ROLE_ADMIN'
        user_db:
            entity:
                class: AppBundle\Entity\User
                property: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                use_forward:
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   /logout
                target: /

        js_router:
            pattern: ^/(js\/routing)
            security: false

    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12

            AppBundle\Entity\User:
                algorithm: bcrypt
                cost: 12

    role_hierarchy:
            ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }