# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    api.url: 'api.openweathermap.org/data/2.5/weather'
    api.key: 'fe7aa0626659cc70bad3797f1ca01004'

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    guzzlehttp.client:
            class:        GuzzleHttp\Client

    cache.adapter:
        class: Symfony\Component\Cache\Adapter\ApcuAdapter


    app.calendar_listener:
        class: AppBundle\EventListener\CalendarEventListener
        arguments:
            doctrine:       '@doctrine'
            token_storage:  '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }


    app.form.type.color:
        class: AppBundle\Form\Type\ColorType
        tags:
            - { name: form.type, alias: color }


#AppBundle\Repository
    app.calendar_event.repository:
        class: AppBundle\Repository\CalendarEventRepository
        arguments:
            doctrine:       '@doctrine'

    app.event_category.repository:
        class: AppBundle\Repository\EventCategoryRepository
        arguments:
            doctrine:       '@doctrine'

#AppBundle\Service
    app.geo.ip.service:
        class: AppBundle\Service\GeoIpService

    app.weather.api.service:
        class: AppBundle\Service\WeatherApiService
        arguments:
            key: '%api.key%'
            url: '%api.url%'
            guzzleClient: '@guzzlehttp.client'
            cacheAdapter: '@cache.adapter'
            geoIpService: '@app.geo.ip.service'